dubbo:
  application:
    name: health-backend
  registry:
    address: zookeeper://192.168.247.129:2181
  scan:
    base-packages: com.java.mobile.controller

server:
  port: 9002

qiniu:
  accessKey: rBh-QfhsoePjLyDnEDWHgh-G2Hzt16vjnrULyFW1
  secretKey: LpNEGn4KSCny1ChssMrp8d42FrG7FxD2dn5IcIZR
  bucket: kanganhealth-j

spring:
  redis:
    host: 192.168.247.129  #redis服务所在的主机ip
    port: 6379
    database: 1  #要连接的数据库，默认是0
    timeout: 30000   # 连接超时时间（毫秒）
    lettuce:
      pool:
        max-wait: -1 #最大阻塞等待时间 (负数表示没限制)
        max-active: 20  # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 5   # 连接池中的最大空闲连接
        min-idle: 0  #  连接池中的最小空闲连接

